### PR TITLE
Ticket #4815: Fix no colored prompt after switching panels off for the first time

### LINKED ISSUE #4815: No colored prompt after switching panels off first time
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Midnight Commander version and build configuration

```shell
git master
```

### Operating system

```shell
any with subshell support
```

### Is this issue reproducible using the latest version of Midnight Commander?

- [x] I confirm the issue is still reproducible with the latest version of Midnight Commander

### How to reproduce

1. Set the `PS1` variable to a colored prompt (see `~/.bashrc` on most distributions)
2. Launch mc in a terminal with subshell support
3. Press `Ctrl+O`
4. A black screen appears, showing only a white prompt
5. Press `Enter`
6. The colored prompt appears from now on

### Expected behavior

After pressing `Ctrl+O`, the colored prompt should appear

### Actual behavior

See above

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by horkykuba**
Fix the issue by strictly distinguishing between `mc_prompt`, which should be stripped using `strip_ctrl_codes()`, and `subshell_prompt`, which should always hold the original, non-stripped `PS1`. Make `mc_prompt` heap-based.

* Resolves: #4815

### CODE REVIEW

File: src/filemanager/layout.c [hunk 1]
```diff
@@ -984,32 +983,26 @@ setup_cmdline (void)
     {
         // Workaround: avoid crash on FreeBSD (see ticket #4213 for details)
         if (subshell_prompt != NULL)
-            tmp_prompt = g_string_free (subshell_prompt, FALSE);
-        else
-            tmp_prompt = g_strdup (mc_prompt);
-        (void) strip_ctrl_codes (tmp_prompt);
+        {
+            g_free (mc_prompt);
+            mc_prompt = g_strdup (subshell_prompt->str);
```
Comment (mc-worker) [inline src/filemanager/layout.c]: You do know the string length, why are you not using it?
```
mc_prompt = g_strndup (subshell_prompt->str, subshell_prompt->len);
```

File: src/main.c [hunk 2]
```diff
@@ -419,7 +419,7 @@ main (int argc, char *argv[])
         enable_bracketed_paste ();
 
         // subshell_prompt is NULL here
-        mc_prompt = (geteuid () == 0) ? "# " : "$ ";
+        mc_prompt = g_strdup ((geteuid () == 0) ? "# " : "$ ");
```
Comment (mc-worker) [inline src/main.c:422]: There is no `g_free (mc_prompt)` later.

File: src/filemanager/layout.c (hunk 1 above)
Comment (horkykuba) [reply src/filemanager/layout.c]: Done

File: src/main.c (hunk 2 above)
Comment (horkykuba) [reply src/main.c:422]: Done

**Comment by horkykuba** [comment]
@aborodin thanks, updated

**Review by mc-worker — APPROVED** [review]
Thanks!

**Review by zyv — APPROVED** [review]
Thank you!
