### PR TITLE
Ticket #4981: do not show color warning with --nocolor

### LINKED ISSUE #4981: --nocolor complains about not enough colors
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Midnight Commander version and build configuration

```shell
4.8.33, git
```

### Operating system

```shell
.
```

### Is this issue reproducible using the latest version of Midnight Commander?

- [x] I confirm the issue is still reproducible with the latest version of Midnight Commander

### How to reproduce

Configure mc to use a skin that uses more colors than the terminal. E.g. mention `xoria256` in the config file or pass `--skin xoria256`, whereas `TERM=xterm` and `COLORTERM` is unset. Or any similar setup.

If you start up mc, you get an error box explaining the mismatching color support situation, and mentioning that the default skin will be used. So far so good.

Now pass mc a `-b` a.k.a. `--nocolor` option.

### Expected behavior

Start up in black and white, without the previous error dialog.

### Actual behavior

The error dialog is still presented.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by peripherium**
## Proposed changes

Suppress the color capability warning when `--nocolor` is used.

The warning is still shown if a skin is explicitly requested via menu.

Additionally, the global variable `mc_skin_is_init` was removed:
it is set with seemingly meaningful values but never actually used.

* Resolves: #4981

## Checklist
- [X] I have referenced the issue(s) resolved by this PR (if any)
- [X] I have signed-off my contribution with `git commit --amend -s`
- [X] Lint and unit tests pass locally with my changes (`make indent && make check`)
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added the necessary documentation (if appropriate)

---

Quick question: in earlier commits I was asked to add a test function
even when the function already existed. Should a test function be
added for every existing function in the future? If so, I can add
one for this change as well.

### CODE REVIEW

**Comment by zyv** [comment]
> Quick question: in earlier commits I was asked to add a test function even when the function already existed. Should a test function be added for every existing function in the future? If so, I can add one for this change as well.

In general, I tend to ask for a test when 1) the changes seem "risky" according to my subjective feeling and 2) it seems to me that they can indeed be tested relatively simply with the current setup.

I mostly have a feeling that changes are "risky" when an old large function full of loops and conditionals, and possibly external variables, which is otherwise not covered with tests, is changed, and likely in a non-trivial fashion.

In this case, I wouldn't demand a test, but, of course, every little bit is welcome, if you feel like it. Our test coverage is very bad, and this is one of the reasons why it's so hard to review PRs in a timely manner. You have to check that the code makes sense and doesn't have unwanted side-effects, and with no test coverage it's mostly a gamble...

**Review by zyv — APPROVED** [review]

File: lib/skin/common.c [hunk 1]
```diff
@@ -149,27 +147,30 @@ mc_skin_init (const gchar *skin_override, GError **mcerror)
     }
     if (is_good_init && mc_skin__default.have_true_colors && !tty_use_truecolors (&error))
     {
-        mc_propagate_error (mcerror, 0,
-                            _ ("Unable to use '%s' skin with true colors support:\n%s\nDefault "
-                               "skin has been loaded"),
-                            mc_skin__default.name, error->message);
+        if (!mc_global.tty.disable_colors
+            || (mc_global.tty.disable_colors && skin_override != NULL))
```
Comment (mc-worker) [inline lib/skin/common.c]: The logical expression `!a || (a && b)` can be optimized to `!a || b`.

File: lib/skin/common.c [hunk 2]
```diff
@@ -149,27 +147,30 @@ mc_skin_init (const gchar *skin_override, GError **mcerror)
...
         is_good_init = FALSE;
     }
     if (is_good_init && mc_skin__default.have_256_colors && !tty_use_256colors (&error))
     {
-        mc_propagate_error (mcerror, 0,
-                            _ ("Unable to use '%s' skin with 256 colors support:\n%s\nDefault "
-                               "skin has been loaded"),
-                            mc_skin__default.name, error->message);
+        if (!mc_global.tty.disable_colors
+            || (mc_global.tty.disable_colors && skin_override != NULL))
```
Comment (mc-worker) [inline lib/skin/common.c]: The same.

**Comment by peripherium** [comment]
> In this case, I wouldn't demand a test, but, of course, every little bit is welcome, if you feel like it. Our test coverage is very bad, and this is one of the reasons why it's so hard to review PRs in a timely manner. You have to check that the code makes sense and doesn't have unwanted side-effects, and with no test coverage it's mostly a gamble...

I took a quick look at this over the weekend and decided to add a test. It turned out to be fairly simple, and writing it was a nice way to better understand this part of the code.

**Comment by peripherium** [comment]
I don't understand why my mc_skin_init() test fails on both Ubuntu and Fedora. Is there a way to look at the log somewhere?

**Comment by zyv** [comment]
> I don't understand why my mc_skin_init() test fails on both Ubuntu and Fedora.

On Fedora, it's a simple formatting issue, and you have accidentally botched a symlink. You can see the log here:

https://github.com/MidnightCommander/mc/actions/runs/23750102108/job/69189411316?pr=5081

> Is there a way to look at the log somewhere?

On Ubuntu, it's more interesting. Maybe something to do with mocking?

```
FAIL: common__mc_skin_init
==========================

Running suite(s): /lib/skin
Running suite /lib/skin
../../../../tests/lib/skin/common__mc_skin_init.c:145:F:Core:skin_test:0: mc_skin_init (data->skin_name, &mcerror) variable should be TRUE
../../../../tests/lib/skin/common__mc_skin_init.c:152:P:Core:skin_test:1: Passed
../../../../tests/lib/skin/common__mc_skin_init.c:152:P:Core:skin_test:2: Passed
../../../../tests/lib/skin/common__mc_skin_init.c:145:F:Core:skin_test:3: mc_skin_init (data->skin_name, &mcerror) variable should be TRUE
../../../../tests/lib/skin/common__mc_skin_init.c:152:P:Core:skin_test:4: Passed
../../../../tests/lib/skin/common__mc_skin_init.c:152:P:Core:skin_test:5: Passed
../../../../tests/lib/skin/common__mc_skin_init.c:145:F:Core:skin_test:6: mc_skin_init (data->skin_name, &mcerror) variable should be TRUE
../../../../tests/lib/skin/common__mc_skin_init.c:145:F:Core:skin_test:7: mc_skin_init (data->skin_name, &mcerror) variable should be TRUE
../../../../tests/lib/skin/common__mc_skin_init.c:152:P:Core:skin_test:8: Passed
../../../../tests/lib/skin/common__mc_skin_init.c:145:F:Core:skin_test:9: mc_skin_init (data->skin_name, &mcerror) variable should be TRUE
../../../../tests/lib/skin/common__mc_skin_init.c:145:F:Core:skin_test:10: mc_skin_init (data->skin_name, &mcerror) variable should be TRUE
../../../../tests/lib/skin/common__mc_skin_init.c:152:P:Core:skin_test:11: Passed
../../../../tests/lib/skin/common__mc_skin_init.c:145:F:Core:skin_test:12: mc_skin_init (data->skin_name, &mcerror) variable should be TRUE
../../../../tests/lib/skin/common__mc_skin_init.c:145:F:Core:skin_test:13: mc_skin_init (data->skin_name, &mcerror) variable should be TRUE
../../../../tests/lib/skin/common__mc_skin_init.c:145:F:Core:skin_test:14: mc_skin_init (data->skin_name, &mcerror) variable should be TRUE
../../../../tests/lib/skin/common__mc_skin_init.c:145:F:Core:skin_test:15: mc_skin_init (data->skin_name, &mcerror) variable should be TRUE
../../../../tests/lib/skin/common__mc_skin_init.c:145:F:Core:skin_test:16: mc_skin_init (data->skin_name, &mcerror) variable should be TRUE
../../../../tests/lib/skin/common__mc_skin_init.c:145:F:Core:skin_test:17: mc_skin_init (data->skin_name, &mcerror) variable should be TRUE
33%: Checks: 18, Failures: 12, Errors: 0
../../../../tests/lib/skin/common__mc_skin_init.c:145:F:Core:skin_test:0: mc_skin_init (data->skin_name, &mcerror) variable should be TRUE
../../../../tests/lib/skin/common__mc_skin_init.c:145:F:Core:skin_test:3: mc_skin_init (data->skin_name, &mcerror) variable should be TRUE
../../../../tests/lib/skin/common__mc_skin_init.c:145:F:Core:skin_test:6: mc_skin_init (data->skin_name, &mcerror) variable should be TRUE
../../../../tests/lib/skin/common__mc_skin_init.c:145:F:Core:skin_test:7: mc_skin_init (data->skin_name, &mcerror) variable should be TRUE
../../../../tests/lib/skin/common__mc_skin_init.c:145:F:Core:skin_test:9: mc_skin_init (data->skin_name, &mcerror) variable should be TRUE
../../../../tests/lib/skin/common__mc_skin_init.c:145:F:Core:skin_test:10: mc_skin_init (data->skin_name, &mcerror) variable should be TRUE
../../../../tests/lib/skin/common__mc_skin_init.c:145:F:Core:skin_test:12: mc_skin_init (data->skin_name, &mcerror) variable should be TRUE
../../../../tests/lib/skin/common__mc_skin_init.c:145:F:Core:skin_test:13: mc_skin_init (data->skin_name, &mcerror) variable should be TRUE
../../../../tests/lib/skin/common__mc_skin_init.c:145:F:Core:skin_test:14: mc_skin_init (data->skin_name, &mcerror) variable should be TRUE
../../../../tests/lib/skin/common__mc_skin_init.c:145:F:Core:skin_test:15: mc_skin_init (data->skin_name, &mcerror) variable should be TRUE
../../../../tests/lib/skin/common__mc_skin_init.c:145:F:Core:skin_test:16: mc_skin_init (data->skin_name, &mcerror) variable should be TRUE
../../../../tests/lib/skin/common__mc_skin_init.c:145:F:Core:skin_test:17: mc_skin_init (data->skin_name, &mcerror) variable should be TRUE
Results for all suites run:
33%: Checks: 18, Failures: 12, Errors: 0
FAIL common__mc_skin_init (exit status: 1)
```

**Comment by peripherium** [comment]
> On Ubuntu, it's more interesting. Maybe something to do with mocking?

I've added a line to my test code (`printf("MOCK: tty_use_256colors()\n");`) that proves, the Ubuntu test ignores the "weak" attribute (`MC_MOCKABLE`). I'm currently comparing my test with other tests that mock functions. Any suggestions or ideas are welcome.

**Review by zyv — APPROVED** [review]
@peripherium I think that I've now fixed the CI and reverted all of your experimental changes. Please have another look.

The problem was that you failed to account for VPATH builds, and so your hacked skin loading wasn't working correctly. The other irritating problem with library linking order is due to #4806. I hope that one day I'll get enough time to fix this. Sorry that it has taken me so long.

@mc-worker @egmontkob, are you fine with the current state of the PR?

**Review by mc-worker — APPROVED** [review]
