### PR TITLE
Ticket #3869: actually use the .netrc password for ftp vfs

### LINKED ISSUE #3869: ftp: fail to retrieve password from .netrc when user is in URL
> [!IMPORTANT]
> This issue was migrated from Trac:
>
> | **Origin** | https://midnight-commander.org/ticket/3869 |
> | :------------- | :------------------------------------------------------------------------------------------------ |
> | **Reporter** | `cri` (cri@….org) |

<p>
I have a proper entry in <tt>~/.netrc</tt> for USERNAME, PASSWORD and HOST.<br />
</p>
<p>
If I try to access the URL <a class="ext-link" href="ftp://HOST/PATH">ftp://HOST/PATH</a>, mc correctly retrieves USERNAME and PASSWORD from <tt>.netrc</tt> and I can log into the FTP host.<br />
</p>
<p>
If I try to access the URL <a class="ext-link" href="ftp://USERNAME@HOST/PATH">ftp://USERNAME@HOST/PATH</a>, mc displays a popup window, asking for the password. Shouldn't it retrieve the password from <tt>.netrc</tt>?<br />
</p>
<p>
I had a look at <a href="https://midnight-commander.org/browser/src/vfs/ftpfs/ftpfs.c#L371">https://midnight-commander.org/browser/src/vfs/ftpfs/ftpfs.c#L371</a><br />
</p>
<p>
shouldn't it be <br />
</p>

```
...`&& path_element->password == NULL`
```
<p>
instead of<br />
</p>

```
...`&& path_element->password != NULL`
```
<p>
?<br />
</p>
<p>
Or am I missing something?<br />
</p>

### PR DESCRIPTION
**Pull request by Vrihub**
## Proposed changes

This fixes #3869, when one wants to log into an ftp server only providing username and hostname, and relies on mc to retrieve the password from the .netrc file. Without this, mc retrieves the password from the .netrc file, but doesn't actually use it to login, and asks the user for a password instead.

Please review, this works for me, but I'm not 100% sure it's the best solution.

* Resolves: #3869

## Checklist

👉 Our coding style can be found here: https://midnight-commander.org/coding-style/ 👈

- [x] I have referenced the issue(s) resolved by this PR (if any)
- [x] I have signed-off my contribution with `git commit --amend -s`
- [x] Lint and unit tests pass locally with my changes (`make indent && make check`)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added the necessary documentation (if appropriate)

### CODE REVIEW

File: src/vfs/ftpfs/ftpfs.c [hunk 1]
```diff
@@ -374,6 +374,9 @@ ftpfs_correct_url_parameters (const vfs_path_element_t *velement)
         // If user is different, remove password
         if (new_user != NULL && strcmp (path_element->user, new_user) != 0)
             MC_PTR_FREE (path_element->password);
+        
+        if (path_element->password == NULL)
+          path_element->password = g_strdup (new_passwd);
```
Comment (mc-worker) [inline src/vfs/ftpfs/ftpfs.c]: There is no reason to duplicate `new_passwd` that is just free'd below.

Comment (zyv) [reply src/vfs/ftpfs/ftpfs.c]: Well, I think this is the safest and easiest way to code that, isn't it? What would be your way of doing it?

I'm more concerned about this introducing a logical mistake. I think this if-block should go above the previous one. Otherwise, it just reverts the effect of the previous condition, but not only for the same user but also for a different user.

Comment (Vrihub) [reply src/vfs/ftpfs/ftpfs.c]: You're right, there's a logical error, but I think the correct way is using `else`, see my latest fixup commit. I've tested the following cases and mc behaves as expected:
- `ftp://host`: uses user and passwd from .netrc
- `ftp://user@host`: uses `user`'s passwd from .netrc 
- `ftp://user_not_in_netrc@host`: asks for `user_not_in_netrc`'s password

Please just confirm that it's ok to use `g_strdup()`, I'm not sure about that, I've used it in analogy with line 364 `path_element->user = g_strdup ("anonymous");`

Comment (Vrihub) [reply src/vfs/ftpfs/ftpfs.c]: > Please just confirm that it's ok to use `g_strdup()`, I'm not sure about that, I've used it in analogy with line 364 `path_element->user = g_strdup ("anonymous");`

Well, if I just do `path_element->password = new_passwd;`, the ftp login fails, and mc segfaults.

Comment (mc-worker) [reply src/vfs/ftpfs/ftpfs.c]: > Well, if I just do `path_element->password = new_passwd;`, the ftp login fails, and mc segfaults.

Because of use-after-free. You can take `new_passwd` in the one branch and free it in the other one.

File: src/vfs/ftpfs/ftpfs.c [hunk 2]
```diff
@@ -374,6 +374,9 @@ ftpfs_correct_url_parameters (const vfs_path_element_t *velement)
         // If user is different, remove password
         if (new_user != NULL && strcmp (path_element->user, new_user) != 0)
             MC_PTR_FREE (path_element->password);
```
Comment (mc-worker) [inline src/vfs/ftpfs/ftpfs.c]: Well, this is pointless because `path_element->password` is NULL (see line 367).

File: src/vfs/ftpfs/ftpfs.c [hunk 3]
```diff
@@ -374,6 +374,9 @@ ftpfs_correct_url_parameters (const vfs_path_element_t *velement)
...
+        else
+            // otherwise, use it
+            path_element->password = g_strdup (new_passwd);
```
Comment (zyv) [inline src/vfs/ftpfs/ftpfs.c]: So in the end, the patch becomes like that, agree?

```suggestion
        // Use the password if it matches the user
        if (new_user != NULL && strcmp (path_element->user, new_user) == 0)
            path_element->password = g_strdup (new_passwd);
```

File: src/vfs/ftpfs/ftpfs.c (hunk 1 above)
Comment (zyv) [reply src/vfs/ftpfs/ftpfs.c]: I actually think that branching free is less safe than duplicating the string. The performance penalty of a few microseconds is negligible, because it isn't in a loop, but if later more code is added, whether to free or not has to be correctly considered in all branches. As we can see, we have a lot of bugs creeping in due to subtle errors in conditions. Using `g_strdup` always, even if it's not really needed, is more like ownership transfer semantics in C++. So it's harder to make a mistake when the code is modified later.

File: src/vfs/ftpfs/ftpfs.c (hunk 3 above)
Comment (Vrihub) [reply src/vfs/ftpfs/ftpfs.c]: I confirm this version passes the three test cases I described in https://github.com/MidnightCommander/mc/pull/4831#discussion_r2470776424

Re the other implementation details (string duplication etc), I'll trust you, because my C knowledge is quite limited.

**Review by zyv — APPROVED** [review]

**Comment by zyv** [comment]
@mc-worker ok?

File: src/vfs/ftpfs/ftpfs.c (hunk 1 above)
Comment (mc-worker) [reply src/vfs/ftpfs/ftpfs.c]: > I actually think that branching free is less safe than duplicating the string. The performance penalty of a few microseconds is negligible, because it isn't in a loop, but if later more code is added, whether to free or not has to be correctly considered in all branches. As we can see, we have a lot of bugs creeping in due to subtle errors in conditions. Using `g_strdup` always, even if it's not really needed, is more like ownership transfer semantics in C++. So it's harder to make a mistake when the code is modified later.

I disagree.

Comment (zyv) [reply src/vfs/ftpfs/ftpfs.c]: So how do you want to have it? Like in the first or second fixup?

Comment (mc-worker) [reply src/vfs/ftpfs/ftpfs.c]: The first fixup is definitely wrong. It has a memory leak. The second one is OK .

Comment (zyv) [reply src/vfs/ftpfs/ftpfs.c]: Alright, if that's what you wanted, let's do it like this, even though I think that this is more dangerous for the reason above - C doesn't have a borrow checker.
