### PR TITLE
4625 slow zsh macos

### LINKED ISSUE #4548: Mc start up is slow on FreeBSD with Bash shell when mc is using a subshell
> [!IMPORTANT]
> This issue was migrated from Trac:
>
> | **Origin** | https://midnight-commander.org/ticket/4548 |
> | :------------- | :------------------------------------------------------------------------------------------------ |
> | **Reporter** | `tonythed1111` (tony@….com) |
> | **Mentions** | `maverick.woo@….com` |

<p>
Mc start up is slow on FreeBSD systems when running a Bash shell and the mc subshell feature is in use. There is an annoying delay of about 1 to 2 seconds during start up of the mc program. This occurs on any FreeBSD version that I have used when running bash as my login shell. The delay does not occur on any Linux system that I have used, it only happens on the FreeBSD systems. On FreeBSD when mc is started as 'mc -u' with no subshell the program starts almost instantly and is the expected behavior. When mc is started as 'mc' which does have a subshell, there is an annoying 1 to 2 second delay before it starts up.<br />
</p>
<p>
What steps will reproduce the problem? <br />
</p>
<ol><li>On any FreeBSD operating system set your login shell to use Bash (any bash version).
</li></ol><ol start="2"><li>On the console or xterm, run 'mc'.
</li></ol><ol start="3"><li>You will observe a 1 to 2 second annoying delay before the program starts up.
</li></ol><ol start="4"><li>Now run 'mc -u'.
</li></ol><ol start="5"><li>You will observe an almost instant start up, which is the expected behavior for mc.
</li></ol><ol start="6"><li>The inclusion of a subshell causes the annoying delay.
</li></ol>

### LINKED ISSUE #4625: mc 4.8.32 slow start on MacOS
> [!IMPORTANT]
> This issue was migrated from Trac:
>
> | **Origin** | https://midnight-commander.org/ticket/4625 |
> | :------------- | :------------------------------------------------------------------------------------------------ |
> | **Reporter** | `emkaroly` (molnarkarol@….com) |
> | **Keywords** | `macOS`, `slow`, `sub`, `shell` |

<p>
I am using mc on linux(ubuntu 22.04) and also on macOS(Sonoma 14.Sequoia 15) on MacOS the start takes several seconds on linux it works fine and start instantly. If I use the "-u"flag on macOS it also start instantly.<br />
The default shell in macOS is zsh if I switch to bash it also start instantly. I don't have any custom bash nor zsh profiles its a fresh new OS installation. The machine is a M4 Pro <tt>MacBook</tt> Pro 14 with 48GB RAM and 1TB SSD. Behavior is same in default Terminal app and iTerm also. <br />
Also when i do sudo mc I get this error:<br />
common.c: unimplemented subshell type 1<br />
read (subshell_pty...): No such file or directory (2)<br />
</p>

### LINKED ISSUE #4723: mc ignores $PS1 on macOS
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Midnight Commander version and build configuration

```shell
GNU Midnight Commander 4.8.33
Built with GLib 2.82.4
Built with S-Lang 2.3.3 with terminfo database
Built with libssh2 1.11.1
With builtin editor
With subshell support as default
With support for background operations
With mouse support on xterm
With internationalization support
With multiple codepages support
Virtual File Systems:
 cpiofs, tarfs, sfs, extfs, ftpfs, sftpfs, shell
Data types:
 char: 8; int: 32; long: 64; void *: 64; size_t: 64; off_t: 64; uintmax_t: 64;
```

### Operating system

```shell
Darwin cat.andromeda.lan 24.5.0 Darwin Kernel Version 24.5.0: Tue Apr 22 19:54:25 PDT 2025; root:xnu-11417.121.6~2/RELEASE_ARM64_T6020 arm64

(MacOS 15.5)
```

### Is this issue reproducible using the latest version of Midnight Commander?

- [x] I confirm the issue is still reproducible with the latest version of Midnight Commander

### How to reproduce

When I start `mc`, it ignores the `PS1` variable I had exported, and resets the prompt to `bash-3.2$`.

This is on MacOS 15.5, with the default shell set to Bash (v. 3.2.57 on Mac)

In `.profile`, I set PS1 as:

    export PS1='\[\e]2; $PWD \a\e[32;1m\]\h:$PWD/$\[\e[0m\] '

But when I start mc, I have:

```
bash-3.2$ echo $PS1
\s-\v\$
bash-3.2$ 
```
I must re-execute the `export PS1=`... command to get back my prompt (though without the colors, but that is ok).

### Expected behavior

The mc subshell should keep the value of `$PS1`

### Actual behavior

`$PS1` gets replaced.

### Additional context

I don't have this problem on a different machine with MacOS 15.5 but with Midnight Commander version 4.8.28

### LINKED ISSUE #4780: Read from pty master in nonblocking mode (due to unlikely deadlock)
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Midnight Commander version and build configuration

```shell
4.8.33-353-g32b7a14c4
```

### Operating system

```shell
any
```

### Is this issue reproducible using the latest version of Midnight Commander?

- [x] I confirm the issue is still reproducible with the latest version of Midnight Commander

### How to reproduce

`src/subshell/common.c` contains the following typical pattern 3 times (#4625 is about to add 2 more):

- `select()` on `mc_global.tty.subshell_pty`, possibly along with other fds
- if other fds were present then check if `mc_global.tty.subshell_pty` is said to contain data
- `read()` from this fd

With tty lines, this standard pattern of reading can cause a lockup. That's because the slave side can perform a `tcflush()`, i.e. revoke the data already placed in the tty line. And this could happen between the `select()` and the blocking `read()` steps.

We should set the master fd to `O_NONBLOCK` (a.k.a. `O_NDELAY`) mode. Either for the duration of the `read()`s only, or once and for all but then make sure to adjust the `write()` / `write_all()` calls to expect that attempting to write to a clogged channel behaves differently and returns immediately (`write_all()` would need to be a `select()`+`write()` loop rather than just a `write()` loop).

I guess a helper `read_nonblock()` method flipping the flag back and forth is the easiest solution for now, until proper glib mainloop-based approach is implemented.

Linux has `preadv2()` that allows to pass flags on a per-call basis (for some reason it uses `RWF_NOWAIT` instead of `O_NONBLOCK`) but it's super non-portable.

### Expected behavior

never to block

### Actual behavior

super unlikely to block

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by egmontkob**
## Proposed changes

Fix slow startup on macOS with zsh, and other related problems also affecting other platforms and shells.

* Resolves: #4625
* Resolves: #4780
* Resolves: #4548
* Resolves: #4723

## Checklist

👉 Our coding style can be found here: https://midnight-commander.org/coding-style/ 👈

- [x] I have referenced the issue(s) resolved by this PR (if any)
- [x] I have signed-off my contribution with `git commit --amend -s`
- [x] Lint and unit tests pass locally with my changes (`make indent && make check`)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added the necessary documentation (if appropriate)

---

This is a reincarnation of closed PR #4784. The patches are essentially unchanged (rebased and a few minor feedback addressed).

I really wanted to address #4253 / #4789 first, i.e. to inject our commands via shell startup files rather than "typing" them to those shells; and rebase this work on top of that. However, as discussed in 4789, I failed to figure out how to do this in `zsh`, it looks like it's not possible. This made me lose motivation and I've abandoned that work, at least for now.

The work in this PR is quite hackish, but so is the problem we're trying to deal with, and the current quite complex codebase. And, unfortunately, I still can't claim I perfectly understand everything, including the suspicious 2 or 3 different ways of handling of sending the Ctrl-C char. It's surely nowhere near the cleanest of my works I've ever made, but honestly I got tired of not seeing a clear solution. It's just not the kind of area I'm comfortable with.

So, IMO, let's land this -- along with remotely related pending PR #4804 --, both have already gotten approval a long time ago but then still the discussion and possible improvements went on. I'm afraid this very PR is not really going to get substantially better, and lack of progress for more than a month clearly shows that I've lost motivation. I suggest that we land these two after a last round of review, and then later (also depending on possible user feedback) iterate further.

### CODE REVIEW

File: src/subshell/common.c [hunk 1]
```diff
@@ -1781,10 +1812,11 @@ flush_subshell (int max_wait_length, int how)
         timeleft.tv_sec = 0;
         timeleft.tv_usec = 0;
 
-        const ssize_t bytes = read (mc_global.tty.subshell_pty, pty_buffer, sizeof (pty_buffer));
+        const ssize_t bytes =
```
Comment (ossilator) [inline src/subshell/common.c:1974]: nit: unrelated re-wrap.

File: src/subshell/common.c [hunk 2]
```diff
@@ -1427,12 +1431,15 @@ do_subshell_chdir (const vfs_path_t *vpath, gboolean force, gboolean update_prom
      * the command prompt before we send the cd command. */
     if (!use_persistent_buffer)
     {
-        write_all (mc_global.tty.subshell_pty, "\003", 1);
-        subshell_state = RUNNING_COMMAND;
-        if (mc_global.shell->type != SHELL_FISH && !feed_subshell (QUIETLY, TRUE))
+        if (subshell_initialized)
```
Comment (ossilator) [inline src/subshell/common.c]: nit: merging the conditional would avoid nesting and the re-indentation.

**Review by ossilator — COMMENTED** [review]
good enough for starters.

it's entirely plausible that there is no _right_ solution for this; after all, mc is operating outside anything normally expected for interactive shells.

File: src/subshell/common.c (hunk 1 above)
Comment (egmontkob) [reply src/subshell/common.c:1974]: `make indent` does these for me.

File: src/subshell/common.c (hunk 2 above)
Comment (egmontkob) [reply src/subshell/common.c]: This is one of the major points where I don't understand the code's intent: `write_all()` is executed even for fish, but then setting `subshell_active` and returning isn't; whereas at the two other cases where we send Ctrl+C `write_all()` is inside the non-fish branch. This is pretty fishy (pun intended) but unfortunately I just don't feel the motivation to figure it all out (understand, and fix if necessary). I just wanted to touch the code as little as possible.

As far as I can see, merging the two nested conditionals would definitely modify the business logic -- I can't tell if for the better or for the worse.

I'm happy to file a new issue about this fishy situation, to be reviewed and possibly fixed one day.

Comment (ossilator) [reply src/subshell/common.c]: i mean with the outer conditional. that's logically just an AND.

Comment (egmontkob) [reply src/subshell/common.c]: Yeah, sorry, I missed that. Will do in a sec.

**Review by zyv — APPROVED** [review]
I'm slowly working through my immense mail backlog and have now made it to this PR... I've looked at all the commits separately and at the code as a whole once again.

To me it looks great now! I can particularly commend @egmontkob for splitting changes into sensible commits with helpful commit messages, and the comments in the code are also really useful.

Not even speaking of all the research and investigation that went into getting to the bottom of it. This is really a remarkable tour de force!

In as far as I'm concerned, I'd like to see it merged now. Okay with you @mc-worker ?

**Review by mc-worker — APPROVED** [review]

**Comment by egmontkob** [comment]
Let's see how it goes...

I'm merging it now, and will give it another round of testing on various OSes in a couple of days (please remind me :))

**Comment by egmontkob** [comment]
Just for the record:

A small startup delay on Solaris, #4812, still isn't fixed. There we'd need to somehow work around an obvious Solaris bug.

**Comment by zyv** [comment]
> Let's see how it goes...
> 
> I'm merging it now, and will give it another round of testing on various OSes in a couple of days (please remind me :))

My zsh startup delay on macOS is gone ❤️ 

```
~ % mc -V   
GNU Midnight Commander 4.8.33-535-g045eab71e
~ % zsh --version
zsh 5.9 (arm64-apple-darwin24.0)
~ % uname -a
Darwin Mac 24.6.0 Darwin Kernel Version 24.6.0: Wed Nov  5 21:33:32 PST 2025; root:xnu-11417.140.69.705.2~1/RELEASE_ARM64_T6030 arm64
```
