### PR TITLE
Tickets #4872, #4873 and #4874: fix 'insert control code' function

### LINKED ISSUE #4872: mcedit: Display corruption (missing header) after inserting literal `^J`
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Midnight Commander version and build configuration

```shell
4.8.33, git
```

### Operating system

```shell
Linux
```

### Is this issue reproducible using the latest version of Midnight Commander?

- [x] I confirm the issue is still reproducible with the latest version of Midnight Commander

### How to reproduce

Start `mcedit`. Type a few random characters into the first line.

Press Ctrl-Q to invoke the "Insert literal" dialog. Press Ctrl-J.

The previously typed characters are gone.

Press the Left arrow. mc goes back to those previously typed characters, but now they occupy the header bar's room.

Interestingly the same doesn't happen if you simply press `J` without Ctrl. Then a newline is inserted and the display is updated as expected.

I guess the vertical positioning isn't adjusted??

### Expected behavior

.

### Actual behavior

.

### Additional context

_No response_

### LINKED ISSUE #4873: mcedit: Insert literal, followed by special key acts weirdly
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Midnight Commander version and build configuration

```shell
4.8.33, git
```

### Operating system

```shell
Linux
```

### Is this issue reproducible using the latest version of Midnight Commander?

- [x] I confirm the issue is still reproducible with the latest version of Midnight Commander

### How to reproduce

In `mcedit` press Ctrl-Q to open the "Insert literal" dialog, then press one of the special keys (like F1..F10, arrows, home-end-pgup-pgdn etc.).

In slang build, a raw byte of value roughly in the 128-160-ish range is inserted.

In ncurses build, often a raw control byte (0-31-ish) is inserted.

### Expected behavior

Do nothing, maybe close the dialog but don't insert anything.

### Actual behavior

Inserts something random, depending on the underlying library's representation of that key.

### Additional context

_No response_

### LINKED ISSUE #4874: mcedit: Insert literal should accept plain non-letters
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Midnight Commander version and build configuration

```shell
4.8.33, git
```

### Operating system

```shell
Linux
```

### Is this issue reproducible using the latest version of Midnight Commander?

- [x] I confirm the issue is still reproducible with the latest version of Midnight Commander

### How to reproduce

`mcedit`, Ctrl-Q to open "Insert literal".

Pressing `a` ... `z`, or `^A` ... `^Z` equally inserts the corresponding control character. It doesn't matter if you hold down Ctrl or not.

The few non-letter symbols that conventially correspond to control characters, namely `@` `[` `\` `]` `^` `_`, have to be pressed with Ctrl. If pressed without, the plain character is inserted rather than the control code.

### Expected behavior

Should equally accept `@` `[` `\` `]` `^` `_` keypresses without Ctrl being held down.

### Actual behavior

They are inserted literally.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by peripherium**
The previous implementation used `ascii_alpha_to_cntrl()`, which assumed
alphabetic input and did not properly validate key codes returned by the
terminal libraries. The function has been renamed to `keycode_to_cntrl()`
and extended to correctly validate and convert key codes.

Changes:

- correctly handle `KEY_M_CTRL` combinations (e.g. `Ctrl+J`).
  - Fixes #4872.

- ignore special keys returned by `get_key_code()` (e.g. function or cursor keys).
  - Fixes #4873.

- extend control mappings for `@ [ \ ] ^ _`.
  - Fixes #4874.

- return `-1` for invalid input and ignore it at the call sites

The function is used both in the *Insert literal* dialog in `mcedit` and in the `mc` command line.

## Checklist
- [X] I have referenced the issue(s) resolved by this PR (if any)
- [X] I have signed-off my contribution with `git commit --amend -s`
- [X] Lint and unit tests pass locally with my changes (`make indent && make check`)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added the necessary documentation (if appropriate)

### CODE REVIEW

**Comment by zyv** [comment]
Since you are fixing `keycode_to_cntrl`, could you please add a test for it? Thank you!

**Comment by zyv** [comment]
@egmontkob adding you, since this PR fixes 3 issues that you have reported...

**Comment by peripherium** [comment]
I initially didn't add a test for this function because the previous implementation didn't have one, so I assumed that adding a test was not required.

In the meantime, I have taken a closer look at the test suite and added the requested test here.

If this test is not sufficient or needs adjustments, please let me know.

File: lib/widget/input.c [hunk 1]
```diff
@@ -1029,8 +1029,13 @@ input_callback (Widget *w, Widget *sender, widget_msg_t msg, int parm, void *dat
     case MSG_KEY:
         if (parm == XCTRL ('q'))
         {
+            int control_code;
             quote = TRUE;
```
Comment (mc-worker) [inline lib/widget/input.c:1032]: Please add an empty line after variable declaration.

File: tests/lib/Makefile.am [hunk 2]
```diff
@@ -25,7 +25,8 @@ TESTS = \
 	utilunix__my_system_fork_fail \
 	utilunix__my_system_fork_child_shell \
 	utilunix__my_system_fork_child \
-	x_basename
+	x_basename \
+	util__keycode_to_cntrl
```
Comment (mc-worker) [inline tests/lib/Makefile.am]: Please move this line upper to make this list sorted alphabetically.

File: tests/lib/util__keycode_to_cntrl.c [hunk 3]
```diff
@@ -0,0 +1,103 @@
+/*
+   lib - keycode_to_cntrl() function testing
+
+   Copyright (C) 2011-2026
+   Free Software Foundation, Inc.
```
Comment (mc-worker) [inline tests/lib/util__keycode_to_cntrl.c:5]: Really 2011?

File: tests/lib/util__keycode_to_cntrl.c [hunk 4]
```diff
@@ -0,0 +1,103 @@
...
+    /*
+     * Invalid inputs are non-ASCII or other special keys.
+     * These have bits set outside of 0x7f and KEY_M_CTRL.
+     */
+    {0x5000, -1}, {128, -1}, {0x0507, -1}
+};
+
+START_PARAMETRIZED_TEST (keycode_test, test_keycodes)
+{
+    int actual_result;
```
Comment (mc-worker) [inline tests/lib/util__keycode_to_cntrl.c]: Please add an empty line after variable declaration.

**Review by mc-worker — COMMENTED** [review]
Formatting issues: 
https://github.com/MidnightCommander/mc/actions/runs/22849421605/job/66290234418

File: lib/util.c [hunk 5]
```diff
@@ -1159,12 +1155,23 @@ save_file_position (const vfs_path_t *filename_vpath, long line, long column, of
 /* --------------------------------------------------------------------------------------------- */
 
 extern int
-ascii_alpha_to_cntrl (int ch)
+keycode_to_cntrl (int ch)
 {
-    if ((ch >= ASCII_A && ch <= ASCII_Z) || (ch >= ASCII_a && ch <= ASCII_z))
-        ch &= 0x1f;
+    // Only KEY_M_CTRL and lowest 7 bits of ch may be set
+    if ((ch & KEY_M_CTRL) != 0 && (ch & ~(KEY_M_CTRL | 0x7f)) != 0)
```
Comment (egmontkob) [inline lib/util.c]: The condition doesn't match the comment above.

File: lib/util.c [hunk 6]
```diff
@@ -1159,12 +1155,23 @@ save_file_position (const vfs_path_t *filename_vpath, long line, long column, of
...
+        return ch & 0x1f;
+
+    if (ch >= '@' && ch <= '_')
+        return ch - '@';
+
+    if (ch >= '`' && ch <= '~')
+        return ch - '`';
 
-    return ch;
+    return -1;
```
Comment (egmontkob) [inline lib/util.c:1177]: Shouldn't you also handle the common practice of Ctrl+`?` as 0x7F ?

File: lib/util.h [hunk 7]
```diff
@@ -264,7 +264,7 @@ void save_file_position (const vfs_path_t *filename_vpath, long line, long colum
 
 /* if ch is in [A-Za-z], returns the corresponding control character,
```
Comment (egmontkob) [inline lib/util.h]: You should update this comment with the additional characters you handle now; also the modified "else" return value.

File: lib/util.c [hunk 8]
```diff
@@ -1159,12 +1155,23 @@ save_file_position (const vfs_path_t *filename_vpath, long line, long column, of
...
 extern int
-ascii_alpha_to_cntrl (int ch)
+keycode_to_cntrl (int ch)
 {
-    if ((ch >= ASCII_A && ch <= ASCII_Z) || (ch >= ASCII_a && ch <= ASCII_z))
-        ch &= 0x1f;
+    // Only KEY_M_CTRL and lowest 7 bits of ch may be set
+    if ((ch & KEY_M_CTRL) != 0 && (ch & ~(KEY_M_CTRL | 0x7f)) != 0)
+        return -1;
+
```
Comment (egmontkob) [inline lib/util.c]: Trailing spaces here, please run `make indent`.

File: lib/util.c [hunk 9]
```diff
@@ -1159,12 +1155,23 @@ save_file_position (const vfs_path_t *filename_vpath, long line, long column, of
...
+        return -1;
+    
+    // User pressed Ctrl+(ch)
+    if ((ch & KEY_M_CTRL) != 0)
+        return ch & 0x1f;
+
+    if (ch >= '@' && ch <= '_')
+        return ch - '@';
+
+    if (ch >= '`' && ch <= '~')
```
Comment (egmontkob) [inline lib/util.c]: Do we need to extend beyond the lowercase ASCII chars?

Ctrl+backtick, Ctrl+`{` etc. are absolutely unconventional ways to denote the control chars, I don't think we should handle them.

**Review by egmontkob — COMMENTED** [review]
The commit message is duplicated.

**Review by egmontkob — COMMENTED** [review]
Tested now, and it indeed fixes those three bugs, thanks!

**Comment by peripherium** [comment]
I included the lowercase characters because I thought it would be user-friendly: even if shift wasn't pressed during input, the corresponding control code can be entered via the dialog. However, this is a bit inconsistent with the last inserted condition, according to which `ch == '?'` returns 0x7f. Should I remove the conditions with the lowercase characters from the code?

**Comment by egmontkob** [comment]
Lowercase letters are absolutely fine, in fact, expected; the user probably won't bother pressing Shift.

What's unnecessary IMHO is support the characters "surrounding" the lowercase letters in the ASCII table: ``` ` ``` `{` `|` `}` `~`. Here it's absolutely reasonable that the user will instead press `@` `[` `\` `]` `^` (or `_` which didn't have a counterpart).

**Comment by peripherium** [comment]
Originally I allowed characters from `´` to `~` because I assumed someone looking at the ASCII table might wonder why those printable characters were excluded.

However, if this is not intuitive and could instead confuse future readers, then it doesn't belong in the code. So I removed it and restricted the range to `a-z`.

**Comment by peripherium** [comment]
> The commit message is duplicated.

Sorry about the duplicated commit message - that must have slipped in during the amend commits while I was updating the patch. I've fixed the commit message now.

Please let me know if there is anything else in the patch that should be improved.

**Review by egmontkob — APPROVED** [review]
Just very quickly skimming through it this time, it looks good, thank you!

(Super minor nitpicking: you add an extra newline to the end of tests/lib/Makefile.am which already has enough (some will say that already has more than enough.))

Let's wait for Andrew's review as well.

File: lib/util.c [hunk 10]
```diff
@@ -1159,12 +1155,26 @@ save_file_position (const vfs_path_t *filename_vpath, long line, long column, of
 /* --------------------------------------------------------------------------------------------- */
 
 extern int
```
Comment (mc-worker) [inline lib/util.c]: I'd remove an `extern` word here.

File: lib/util.h [hunk 11]
```diff
@@ -262,9 +262,9 @@ void load_file_position (const vfs_path_t *filename_vpath, long *line, long *col
 void save_file_position (const vfs_path_t *filename_vpath, long line, long column, off_t offset,
                          GArray *bookmarks);
 
-/* if ch is in [A-Za-z], returns the corresponding control character,
- * else returns the argument. */
-extern int ascii_alpha_to_cntrl (int ch);
+/* Return the control character corresponding to key code ch,
+   or -1 if ch cannot be represented as a control character. */
+extern int keycode_to_cntrl (int ch);
```
Comment (mc-worker) [inline lib/util.h]: I'd remove an `extern` word here too.

**Review by mc-worker — COMMENTED** [review]
Please begin the commit message with following line:

`Ticket #4872, #4873, #4874: fix 'insert control code' function`.

**Comment by mc-worker** [comment]
1. Not all test are passed. `util__keycode_to_cntrl.log` is attached.
[util__keycode_to_cntrl.log](https://github.com/user-attachments/files/25976768/util__keycode_to_cntrl.log)

2. In editor, I use a paste of `\t` via "Insert literal" dialog (`ctrl-q`) very often. It doesn't work anymore.

**Comment by peripherium** [comment]
I completely forgot to adjust the test after changing the `keycode_to_cntrl()` function. Thanks for pointing that out. I've already implemented all the other changes (especially in Makefile.am).

**Review by zyv — APPROVED** [review]
I'm happy with the code now, and I’m very happy about the test. Thank you very much! How about the others?

**Review by mc-worker — APPROVED** [review]

**Comment by egmontkob** [comment]
Looked good to me the last time, won't check it again :P Thanks!
