### PR TITLE
Ticket #4144: fix build with ncurses-5.9

### LINKED ISSUE #4144: mouse clicks don't work on ncurses-6.2, generate garbage to stdout
> [!IMPORTANT]
> This issue was migrated from Trac:
>
> | **Origin** | https://midnight-commander.org/ticket/4144 |
> | :------------- | :------------------------------------------------------------------------------------------------ |
> | **Reporter** | `slyfox` (@trofi) |
> | **Mentions** | `egmont` (@egmontkob) |

<p>
It's forward of downstream <a class="ext-link" href="https://bugs.gentoo.org/753578">https://bugs.gentoo.org/753578</a> report.<br />
</p>
<p>
When mc is built with ncurses-6.2 mouse keypresses in xterm don't work and generate garbage output. The following workaround seems to be enough to fix it locally:<br />
</p>

```diff
--- a/lib/tty/key.c
+++ b/lib/tty/key.c
@@ -2124,8 +2124,7 @@ tty_get_event (struct Gpm_Event *event, gboolean redo_event, gboolean block)
         gboolean extended = c == MCKEY_EXTENDED_MOUSE;

 #ifdef KEY_MOUSE
-        extended = extended || (c == KEY_MOUSE && xmouse_seq == NULL
-                                && xmouse_extended_seq != NULL);
+        extended = extended || (c == KEY_MOUSE && xmouse_extended_seq != NULL);
 #endif /* KEY_MOUSE */

         xmouse_get_event (event, extended);
```

```
$ LANG=C ./src/mc --version
GNU Midnight Commander 4.8.25-59-ga2bccac62
Built with GLib 2.64.5
Built with ncursesw 6.2
With builtin Editor
With subshell support as default
With support for background operations
With mouse support on xterm
With support for X11 events
With internationalization support
With multiple codepages support
With ext2fs attributes support
Virtual File Systems:
 cpiofs, tarfs, sfs, extfs, ftpfs, sftpfs, fish
Data types:
 char: 8; int: 32; long: 64; void *: 64; size_t: 64; off_t: 64;
```
<p>
Some details:<br />
</p>

```
$ tput kmous | cat -v
^[[<
$ echo $TERM
xterm-256color
```
<p>
Actual generated sequences by xterm are in form of "\e[&lt;0;10;28M", but mc expects-non-extended form of "\e[bxy".<br />
</p>

### PR DESCRIPTION
**Pull request by zyv**
In some versions, `NCURSES_WIDECHAR` can be defined but empty, so treat it as undefined in this case. This seems to be supported by the latest ncurses source code, which uses the following condition in tests:

```
defined(NCURSES_WIDECHAR) && (NCURSES_WIDECHAR - 0 < 1)
```

Resolves: #4144

### CODE REVIEW

**Comment by egmontkob** [comment]
👍

**Review by egmontkob — APPROVED** [review]

File: lib/tty/tty-ncurses.h [hunk 1]
```diff
@@ -27,7 +27,7 @@
 #endif
 
 /* do not draw shadows if NCurses is built with --disable-widec */
-#if defined(NCURSES_WIDECHAR) && NCURSES_WIDECHAR
+#if defined(NCURSES_WIDECHAR) && (NCURSES_WIDECHAR - 0 < 1)
```
Comment (ossilator) [inline lib/tty/tty-ncurses.h:30]: the `<` makes me really wonder.
from the context, `==` would seem more logical in this case.

Comment (zyv) [reply lib/tty/tty-ncurses.h:30]: I'm not sure why @ThomasDickey did it like this, but in the particular case, I'd rather see mimicking him the best and safest course of action.

**Comment by zyv** [comment]
@mc-worker ok?

**Review by mc-worker — APPROVED** [review]

**Comment by egmontkob** [comment]
This change was broken, see #4817.
