### PR TITLE
Ticket #5062: Ignore mouse click on a menu's separator line

### LINKED ISSUE #5062: Menu: Clicking on separator invokes focused entry
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Midnight Commander version and build configuration

```shell
4.8.33, git
```

### Operating system

```shell
.
```

### Is this issue reproducible using the latest version of Midnight Commander?

- [x] I confirm the issue is still reproducible with the latest version of Midnight Commander

### How to reproduce

Open one of the the F9 menus, let's say Options. One of its entries (by default the first one, e.g. "Configuration") is highlighted.

Click with the mouse on one of the horizontal separator lines between entries.

### Expected behavior

Either nothing, or close the menu.

### Actual behavior

The highlighted entry (e.g. Configuration) is invoked.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by egmontkob**
## Proposed changes

Ignore mouse click on a menu's separator line

* Resolves: #5062

## Checklist

👉 Our coding style can be found here: https://midnight-commander.org/coding-style/ 👈

- [x] I have referenced the issue(s) resolved by this PR (if any)
- [x] I have signed-off my contribution with `git commit --amend -s`
- [x] Lint and unit tests pass locally with my changes (`make indent && make check`)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added the necessary documentation (if appropriate)

### CODE REVIEW

**Review by zyv — COMMENTED** [review]
👍

**Review by zyv — APPROVED** [review]

File: lib/widget/menu.c [hunk 1]
```diff
@@ -728,17 +728,22 @@ menubar_get_menu_by_x_coord (const WMenuBar *menubar, int x)
...
     const WRect *w = &CONST_WIDGET (menubar)->rect;
     menu_t *menu;
+    menu_entry_t *entry;
     int left_x, right_x, bottom_y;
 
     if (!menubar->is_dropped)
         return FALSE;
 
     menu = MENU (g_list_nth_data (menubar->menu, menubar->current));
+    entry = MENUENTRY (g_list_nth_data (menu->entries, y - 2));
```
Comment (mc-worker) [inline lib/widget/menu.c:746]: If entry is NULL, we can immediately return FALSE. Following calculations are not make sense in this case.

**Review by mc-worker — APPROVED** [review]

File: lib/widget/menu.c (hunk 1 above)
Comment (egmontkob) [reply lib/widget/menu.c:746]: Done.

**Comment by zyv** [comment]
:shipit: LGTM

**Comment by egmontkob** [comment]
Oops, just after merging I've realized that the commit message isn't quite accurate. Clicking on a separator line isn't ignored, it closes the menu. Nevermind :)
